import type { ModuleManifest } from "@/types";

// ════════════════════════════════════════════════════════════════
// Manifiesto global de módulos — única fuente de verdad para la nav.
// El Home grid + la búsqueda + el router consumen esta lista.
// El orden acá es el orden visual en el Home.
// ════════════════════════════════════════════════════════════════

export const MODULES: ModuleManifest[] = [
  {
    id: "reuma",
    slug: "reuma",
    name: "Reumatología",
    tagline: "Artritis, conectivopatías, infecciosas y FRA",
    icon: "🦴",
    accent: "#f472b6",
    tags: ["artritis", "reumatoide", "lupus", "sjogren", "esclerosis", "fra", "fibromialgia"],
    kind: "clinico",
  },
  {
    id: "inmuno",
    slug: "inmuno",
    name: "Inmunología",
    tagline: "Innata vs adaptativa, Ig, citocinas y blancos terapéuticos",
    icon: "🛡️",
    accent: "#60a5fa",
    tags: ["inmunidad", "linfocitos", "anticuerpos", "citocinas"],
    kind: "basico",
  },
  {
    id: "triadas",
    slug: "triadas",
    name: "Tríadas y Pirámides",
    tagline: "Combos clásicos que el examen pregunta sí o sí",
    icon: "🔺",
    accent: "#e879f9",
    tags: ["triada", "piramide", "pearls"],
    kind: "herramienta",
  },
  {
    id: "cirugia",
    slug: "cirugia",
    name: "Cirugía",
    tagline: "Abdomen agudo, hernias, quemados y trauma quirúrgico",
    icon: "🔪",
    accent: "#a78bfa",
    tags: ["cirugia", "abdomen", "hernia", "quemados", "apendicitis"],
    kind: "clinico",
  },
  {
    id: "emergencias",
    slug: "emergencias",
    name: "Emergencias",
    tagline: "ACLS, shock, trauma — lo que aparece de guardia",
    icon: "🚨",
    accent: "#ef4444",
    tags: ["acls", "shock", "rcp", "emergencia"],
    kind: "clinico",
  },
  {
    id: "anatomia",
    slug: "anatomia",
    name: "Anatomía",
    tagline: "Puntos quirúrgicos, mapas y nervios con SVG",
    icon: "🧠",
    accent: "#34d399",
    tags: ["anatomia", "nervios", "puntos"],
    kind: "basico",
  },
  {
    id: "epidemiologia",
    slug: "epidemiologia",
    name: "Epidemiología",
    tagline: "Estudios, sesgos, sensibilidad/especificidad",
    icon: "📊",
    accent: "#60a5fa",
    tags: ["epi", "estudios", "casos-control", "cohorte"],
    kind: "basico",
  },
  {
    id: "labs",
    slug: "labs",
    name: "Laboratorio",
    tagline: "Valores de referencia y cómo interpretar cada analito",
    icon: "🧪",
    accent: "#34d399",
    tags: ["labs", "hemograma", "perfil", "valores"],
    kind: "herramienta",
  },
  {
    id: "receptores",
    slug: "receptores",
    name: "Receptores",
    tagline: "Catálogo farmacológico de receptores con efectos clínicos",
    icon: "🔑",
    accent: "#a78bfa",
    tags: ["receptores", "farmaco", "agonistas", "antagonistas"],
    kind: "basico",
  },
  {
    id: "mediadores",
    slug: "mediadores",
    name: "Mediadores",
    tagline: "Hormonas, citocinas y mediadores químicos",
    icon: "💧",
    accent: "#06b6d4",
    tags: ["mediadores", "hormonas", "citocinas"],
    kind: "basico",
  },
  {
    id: "generalidades",
    slug: "generalidades",
    name: "Generalidades",
    tagline: "Bases comunes — semiología, signos vitales, propedéutica",
    icon: "📚",
    accent: "#94a3b8",
    tags: ["generalidades", "semiologia", "propedeutica"],
    kind: "basico",
  },
  {
    id: "trauma",
    slug: "trauma",
    name: "Trauma — Unidad 1",
    tagline: "Politraumatizado, ATLS, manejo inicial",
    icon: "🩹",
    accent: "#fb923c",
    tags: ["trauma", "atls", "politraumatizado", "glasgow"],
    kind: "clinico",
  },
  {
    id: "vocabulario",
    slug: "vocabulario",
    name: "Vocabulario Médico",
    tagline: "Decoder de raíces, prefijos y sufijos con SVG anatómicos",
    icon: "🔤",
    accent: "#fbbf24",
    tags: ["vocabulario", "etimologia", "raices", "prefijos"],
    kind: "herramienta",
  },
  {
    id: "salud_mental",
    slug: "salud-mental",
    name: "Salud Mental",
    tagline: "Psicosis, neurosis, TCA, sueño, impulsividad",
    icon: "🧠",
    accent: "#a78bfa",
    tags: ["psiquiatria", "salud mental", "ansiedad", "depresion", "tca"],
    kind: "clinico",
  },
  {
    id: "links",
    slug: "links",
    name: "Recursos",
    tagline: "Links curados a guías, calculadoras y referencias",
    icon: "🔗",
    accent: "#60a5fa",
    tags: ["links", "recursos", "guias"],
    kind: "herramienta",
  },
];

export function findModule(slug: string): ModuleManifest | undefined {
  return MODULES.find((m) => m.slug === slug);
}
