// ══════════════════════════════════════════════════════════════
// REGISTRY · Flashcards y Quiz indexados por tema · Para hubs globales
// ══════════════════════════════════════════════════════════════

var DECKS={
  anxiety:{
    meta:{name:"anxiety",label:"Ansiedad",icon:"🫀",color:C.anx},
    flash:[
         {q:"¿Cuándo la ansiedad se convierte en trastorno?",r:"Cuando es excesiva, sin causa real proporcional, persiste en el tiempo (generalmente ≥ 6 meses) e interfiere con el funcionamiento diario."},
         {q:"¿Cuál es la diferencia entre un ataque de pánico y el trastorno de pánico?",r:"El ataque de pánico es un episodio aislado (puede ocurrir en cualquier trastorno). El trastorno de pánico requiere ataques recurrentes inesperados con ≥ 1 mes de consecuencias psicológicas o conductuales."},
         {q:"¿Qué es el mutismo selectivo y cómo se diferencia de la timidez?",r:"Es la incapacidad de hablar en situaciones sociales específicas pese a poder hacerlo en otros contextos. La timidez es normal y no impide la comunicación; el mutismo selectivo sí lo hace de forma persistente (≥ 1 mes)."},
         {q:"¿Cuántos síntomas del ataque de pánico se requieren para diagnosticarlo?",r:"Al menos 4 de los 13 síntomas descritos en el DSM-5, de inicio abrupto y que alcanzan la máxima intensidad en minutos."},
         {q:"¿Por qué los pacientes con trastorno de pánico suelen consultar primero a cardiólogos, neumólogos y neurólogos?",r:"Porque los síntomas físicos (palpitaciones, disnea, dolor precordial, parestesias) son prominentes y simulan enfermedades orgánicas antes de que se identifique el origen ansioso."},
         {q:"¿Cuál es el rol del locus coeruleus en el trastorno de pánico?",r:"Es el centro de alarma del tronco encefálico, regulador de noradrenalina. En el trastorno de pánico está hipersensible, lo que facilita la activación del sistema de alerta ante estímulos mínimos."},
         {q:"¿Qué es la teoría de la 'falsa sofocación' en el trastorno de pánico?",r:"Una hipersensibilidad al CO₂: el cerebro interpreta erróneamente señales de asfixia → desencadena hiperventilación y pánico incluso sin peligro real."},
         {q:"¿Cuántos síntomas se requieren para el diagnóstico del TAG y durante cuánto tiempo?",r:"Al menos 3 de 6 síntomas (en adultos; 1 en niños) presentes la mayoría de los días por ≥ 6 meses."},
         {q:"¿Cuáles son los ISRS de primera línea para los trastornos de ansiedad?",r:"Fluoxetina, paroxetina y sertralina. Para el TAG se prefiere paroxetina o escitalopram."},
         {q:"¿Qué diferencia a la fobia específica de la fobia social?",r:"En la fobia específica el miedo se dirige a un objeto/situación concreta (animales, alturas). En la fobia social el miedo es al escrutinio y evaluación negativa por parte de otros en situaciones sociales."},
         {q:"¿Por qué se desaconseja el consumo de cafeína en el trastorno de pánico?",r:"La cafeína es un estimulante del SNC que puede desencadenar o intensificar ataques de pánico al activar el sistema adrenérgico."},
         {q:"¿Qué comorbilidades son más frecuentes en el trastorno de ansiedad generalizada?",r:"Depresión mayor y trastorno por uso de sustancias."},
         {q:"¿Cuál es la duración mínima recomendada del tratamiento farmacológico en el trastorno de pánico?",r:"Mínimo 1 año tras la remisión de los síntomas, para evitar recaídas."},
         {q:"¿Qué diferencia al TAG del trastorno de pánico?",r:"En el TAG la ansiedad es crónica, difusa y sobre múltiples temas. En el TP hay episodios agudos e inesperados de terror máximo con síntomas físicos intensos."},
         {q:"¿Cuántas situaciones de los 5 grupos deben temerse para diagnosticar agorafobia?",r:"Al menos 2 de las 5 situaciones (transporte público, espacios abiertos, lugares cerrados, multitudes, salir solo de casa)."}
       ],
    quiz:[
       {p:"Hombre de 28 años con 4 episodios en el último mes de palpitaciones súbitas, disnea, temblor y miedo a morir. Pico en 8 min, duración 25 min. Inicia a evitar el metro. TSH y ECG normales. ¿Dx más probable?",
        o:["TAG","Trastorno de pánico (+ agorafobia a codiagnosticar)","Fobia específica situacional","Hipertiroidismo subclínico"],r:1,
        x:"Crisis inesperadas recurrentes + >1 mes de cambio conductual (evitación del metro) → trastorno de pánico. La evitación activa de transporte público cumple agorafobia, que desde DSM-5 se codiagnostica de forma independiente."},
       {p:"Mujer de 35 años con 8 meses de preocupación excesiva por trabajo, hijos y dinero, con tensión muscular, fatiga, irritabilidad y sueño no reparador. TSH normal. ¿Tratamiento de primera línea?",
        o:["Clonazepam 1 mg BID crónico","Escitalopram 10 mg/día (titular a 20)","Propranolol 40 mg BID","Buspirona como monoterapia"],r:1,
        x:"TAG. Primera línea: ISRS o IRSN (escitalopram o sertralina, venlafaxina, duloxetina). BZD solo como puente corto. Buspirona es coadyuvante, no monoterapia habitual. Propranolol no tiene rol."},
       {p:"¿Tratamiento de elección para fobia específica a las arañas?",
        o:["Sertralina 100 mg/día","Exposición in vivo (TCC)","Clonazepam a demanda","Propranolol pre-exposición"],r:1,
        x:"Las fobias específicas NO tienen farmacoterapia de primera línea. El tratamiento de elección es la exposición in vivo (terapia cognitivo-conductual)."},
       {p:"Niña de 7 años se marea, se pone pálida y se desmaya cada vez que se le saca sangre. ¿Fobia y técnica de manejo?",
        o:["Situacional · respiración diafragmática","Sangre-inyección-daño · tensión aplicada","TAG · relajación muscular progresiva","Social · entrenamiento asertivo"],r:1,
        x:"Fobia SID = única con respuesta vasovagal bifásica (taquicardia → bradicardia → hipotensión → síncope). La tensión aplicada (tensar músculos grandes durante 15 s) eleva la PA y previene el síncope."},
       {p:"Paciente con pánico inicia sertralina 50 mg/día. A los 10 días refiere estar PEOR, con más crisis de pánico. ¿Conducta correcta?",
        o:["Suspender y cambiar a paroxetina","Explicar que es activación inicial esperable y eventualmente añadir BZD como puente corto","Subir a 200 mg/día ya","Cambiar a buspirona"],r:1,
        x:"Activación inicial: aumento de síntomas ansiosos en los primeros 7–14 días de ISRS, esperable en ansiosos. Por eso se recomienda iniciar a MITAD de dosis. Puente con BZD si es muy intensa. No es fracaso terapéutico."},
       {p:"Mujer de 45 con miedo intenso a hablar en reuniones de trabajo (casi se desmaya). No tiene problemas en situaciones sociales informales. ¿Opción con mejor relación costo-beneficio?",
        o:["Sertralina 100 mg/día crónica","Propranolol 20 mg tomado 45 min antes de cada reunión","Clonazepam crónico","Exposición in vivo sola"],r:1,
        x:"Fobia social tipo ACTUACIÓN (performance only). Propranolol a demanda 30–60 min antes es muy efectivo para este subtipo. ISRS se reserva para fobia social generalizada."}
     ]
  },
  psicosis:{
    meta:{name:"psicosis",label:"Psicosis",icon:"🔺",color:C.psi},
    flash:[
         {q:"¿Cuál es la diferencia fundamental entre psicosis y neurosis?",r:"La prueba de realidad. En psicosis hay PÉRDIDA del contacto con la realidad (alucinaciones, delirios). En neurosis se mantiene (ansiedad, depresión, obsesiones)."},
         {q:"¿Cómo se distinguen psicosis breve, esquizofreniforme y esquizofrenia?",r:"Solo por duración. Psicótico breve: ≥1 día pero <1 mes, con retorno al estado previo. Esquizofreniforme: ≥1 mes, <6 meses. Esquizofrenia: ≥6 meses. La clínica es la misma."},
         {q:"¿Cuál es la diferencia clave entre esquizoafectivo y trastorno del ánimo con psicosis?",r:"En esquizoafectivo debe haber ≥2 SEMANAS de delirios o alucinaciones SIN síntomas afectivos mayores a lo largo de la enfermedad. Si la psicosis aparece SOLO dentro del episodio afectivo, es trastorno bipolar/depresivo con psicosis, no esquizoafectivo."},
         {q:"¿Cuáles son los 2 subtipos del trastorno esquizoafectivo?",r:"Tipo bipolar (con episodios maníacos, con o sin depresión mayor) y tipo depresivo (solo con episodios depresivos mayores). El bipolar tiene mejor pronóstico."},
         {q:"¿Qué porcentaje del trastorno esquizofreniforme progresa a esquizofrenia?",r:"Aproximadamente dos tercios (~⅔). El pronóstico mejora con las características favorables: inicio rápido de síntomas prominentes, confusión/perplejidad, buen funcionamiento previo, ausencia de aplanamiento afectivo."},
         {q:"¿Cuántos síntomas se requieren para un episodio maníaco y durante cuánto tiempo?",r:"≥3 de 7 síntomas (≥4 si el ánimo es solo irritable) durante ≥1 semana. O cualquier duración si requiere hospitalización o hay psicosis."},
         {q:"¿Qué diferencia la hipomanía de la manía?",r:"Hipomanía: ≥4 días, sin deterioro marcado, sin psicosis, no requiere hospitalización. Manía: ≥1 semana, con deterioro o psicosis. Si hay psicosis, por definición es manía."},
         {q:"¿Cuál es la forma más grave de bipolaridad?",r:"Bipolar tipo I. Requiere solo un episodio maníaco (la depresión no es necesaria, aunque es frecuente)."},
         {q:"¿Cuál es el tratamiento de elección para la depresión bipolar?",r:"Lamotrigina (prevención), litio, quetiapina. Los antidepresivos solo se usan con estabilizador de base por riesgo de viraje maníaco."},
         {q:"¿Cuántos síntomas se requieren para el diagnóstico de depresión mayor y durante cuánto tiempo?",r:"≥5 de 10 síntomas durante ≥2 semanas, casi todos los días. Al menos uno debe ser ánimo deprimido o anhedonia."},
         {q:"¿Cuáles son los 5 tipos de trastorno delirante?",r:"Persecutorio (el más común · puede ser hostil), erotomaníaco, grandeza, celotípico (puede ser hostil) y somático."},
         {q:"¿Qué diferencia el delirante somático de la hipocondría?",r:"En el trastorno delirante somático, el delirio NO desaparece con pruebas médicas normales (la convicción es fija). En la hipocondría/IAD, la preocupación persiste pero puede haber dudas."},
         {q:"¿Qué tipo de esquizofrenia tiene peor pronóstico?",r:"La desorganizada (hebefrénica): comienzo precoz y grave, afecta las emociones."},
         {q:"¿Qué subtipo de esquizofrenia es el más frecuente?",r:"El paranoide: predominan los síntomas positivos, afecta el pensamiento, pronóstico favorable."},
         {q:"Menciona las 4 vías dopaminérgicas y qué pasa si fallan.",r:"Mesolímbica → síntomas positivos de esquizofrenia. Mesocortical → síntomas negativos. Nigroestriada → Parkinson/extrapiramidalismo. Tuberoinfundibular → hiperprolactinemia."},
         {q:"¿Cuáles son los síntomas positivos y negativos de la esquizofrenia?",r:"Positivos: alucinaciones, delirios, pensamiento desorganizado. Negativos: aplanamiento afectivo, abulia, anhedonia, alogia (↓ habla), aislamiento social."},
         {q:"¿Cuál es la duración mínima para diagnosticar esquizofrenia?",r:"≥1 mes de síntomas activos del criterio A (al menos uno debe ser delirio, alucinación o discurso desorganizado) + signos continuos del trastorno durante ≥6 meses."},
         {q:"¿Cuál es el único antipsicótico eficaz en esquizofrenia refractaria y qué riesgo tiene?",r:"Clozapina. Riesgo de agranulocitosis fatal. Requiere hemograma semanal los primeros 6 meses, luego mensual."},
         {q:"¿Cuáles son los factores de riesgo de suicidio en esquizofrenia?",r:"Sexo masculino, menor de 30 años, desempleo, depresión previa, antecedentes de abuso de sustancias, internación reciente."},
         {q:"¿Qué precipitantes pueden causar recaídas en bipolaridad?",r:"Mala adherencia al tratamiento, alteraciones del sueño (dormir mucho o poco), drogas y automedicación (café, THC, alcohol), mala medicación por diagnóstico incorrecto."}
       ],
    quiz:[
       {p:"Varón de 45 años convencido hace 8 meses de que su esposa lo engaña. Ha contratado detectives sin encontrar evidencia pero su convicción se mantiene. Trabaja normalmente, no hay alucinaciones ni otros síntomas. ¿Dx más probable?",
        o:["Esquizofrenia paranoide","Trastorno delirante celotípico","Bipolar I con síntomas psicóticos","Trastorno de personalidad paranoide"],r:1,
        x:"Delirio ≥1 mes + personalidad preservada + funcional + sin alucinaciones prominentes = trastorno delirante. El celotípico es uno de los subtipos hostiles."},
       {p:"Mujer de 26 años con 10 días de ánimo elevado, solo duerme 3 horas, habla sin parar, ha gastado $15,000 en compras compulsivas y dice tener 'un mensaje divino'. Requirió hospitalización. ¿Dx?",
        o:["Hipomanía en bipolar II","Episodio maníaco en bipolar I","Esquizofrenia paranoide","Trastorno ciclotímico"],r:1,
        x:"Duración >1 semana + deterioro marcado (compras, hospitalización) + síntomas psicóticos (mensaje divino) = episodio MANÍACO. La presencia de psicosis por definición hace que sea manía, no hipomanía. Esto clasifica el cuadro como bipolar I."},
       {p:"Varón de 30 años con 3 semanas de ánimo deprimido, anhedonia, insomnio, fatiga, pensamientos de muerte, pérdida de peso y sentimientos de inutilidad. Sin antecedentes de manía ni hipomanía. ¿Dx y primera línea?",
        o:["Distimia · psicoterapia","Trastorno depresivo mayor · ISRS + TCC","Ciclotimia · lamotrigina","Duelo complicado · apoyo"],r:1,
        x:"≥5 de 10 síntomas durante ≥2 semanas + anhedonia = depresión mayor. 1ª línea: ISRS (sertralina, escitalopram, fluoxetina) combinado con TCC."},
       {p:"Mujer de 22 años con alucinaciones auditivas, delirios de persecución, discurso desorganizado y aplanamiento afectivo durante los últimos 8 meses. Dejó los estudios y se aisló. ¿Dx?",
        o:["Psicosis breve","Esquizofrenia","Trastorno delirante","Episodio psicótico inducido por sustancias"],r:1,
        x:"≥2 síntomas del criterio A (alucinaciones, delirios, discurso desorganizado) + duración ≥6 meses + deterioro funcional marcado + síntomas negativos (aplanamiento) = esquizofrenia."},
       {p:"Paciente bipolar I sin respuesta a 2 antipsicóticos. Se considera clozapina. ¿Qué monitoreo es obligatorio?",
        o:["Función tiroidea mensual","Hemograma semanal los primeros 6 meses, luego mensual","ECG con QT cada 3 meses","Niveles plasmáticos quincenales"],r:1,
        x:"Clozapina tiene riesgo de AGRANULOCITOSIS fatal. Protocolo: hemograma semanal los primeros 6 meses, luego mensual mientras dure el tratamiento."},
       {p:"¿Cuál de las siguientes NO es una vía dopaminérgica afectada en esquizofrenia?",
        o:["Mesolímbica","Mesocortical","Nigroestriada","Tuberoinfundibular"],r:2,
        x:"La nigroestriada (sustancia nigra → cuerpo estriado) NO está afectada en esquizofrenia sino en Parkinson. Su bloqueo por antipsicóticos típicos causa extrapiramidalismo. Las vías afectadas en esquizofrenia son mesolímbica (síntomas positivos) y mesocortical (síntomas negativos)."}
     ]
  },
  toc:{
    meta:{name:"toc",label:"TOC",icon:"🔁",color:C.toc},
    flash:[
         {q:"¿Cuál es la diferencia entre obsesión y compulsión?",r:"Obsesión: pensamiento/imagen/impulso intrusivo recurrente que genera ansiedad. Compulsión: conducta o acto mental que el paciente realiza para reducir la ansiedad o prevenir un suceso temido."},
         {q:"¿Cuánto tiempo debe durar una obsesión/compulsión al día para diagnosticar TOC?",r:"Más de 1 hora al día, o que cause malestar o deterioro clínicamente significativo."},
         {q:"¿Cuáles son las 4 dimensiones clínicas del TOC?",r:"1) Contaminación + lavado, 2) Simetría/orden + 'just right', 3) Daño/responsabilidad + comprobación, 4) Contenido prohibido/tabú + actos mentales."},
         {q:"¿Cuál es la dosis de sertralina para TOC vs depresión?",r:"TOC: 150–200 mg/día. Depresión: 50–100 mg/día. El TOC requiere el DOBLE de dosis."},
         {q:"¿En cuánto tiempo se espera respuesta completa al ISRS en TOC?",r:"10–12 semanas (no 4–6 como en depresión). No cambies de fármaco antes si hay mejoría parcial a las 6 semanas."},
         {q:"¿Cuál es el gold standard psicoterapéutico del TOC?",r:"Exposición y Prevención de Respuesta (EPR): exposición gradual al disparador + impedir la compulsión. Equivalente o superior a fármacos aislados."},
         {q:"¿Qué es PANDAS?",r:"Pediatric Autoimmune Neuropsychiatric Disorders Associated with Streptococcus. TOC de inicio SÚBITO en niño post-faringitis estreptocócica. Tratamiento: antibiótico + manejo estándar del TOC."},
         {q:"¿Por qué NUNCA se debe autorizar cirugía cosmética en TDC?",r:"Empeora el cuadro: el cerebro reinterpreta el nuevo aspecto como otro defecto. Riesgo suicida 4× mayor en TDC — screening de suicidio obligatorio."},
         {q:"¿Cuál es el tratamiento de 1ª línea en tricotilomanía?",r:"Terapia de Reversión de Hábito (TRH). N-acetilcisteína 1200–2400 mg/día tiene buena evidencia. ISRS eficacia limitada."},
         {q:"¿Qué antipsicótico se prefiere para augmentar un ISRS en TOC con tics?",r:"Aripiprazol 5–15 mg/día. Risperidona 0.5–3 mg sin tics."},
         {q:"¿Cuánto tiempo se mantiene el tratamiento tras remisión del TOC?",r:"Mínimo 1–2 años tras remisión total. El riesgo de recaída es alto al suspender."},
         {q:"¿Cuál es la diferencia entre TDC y trastorno delirante somático?",r:"En TDC la creencia es sobre la APARIENCIA (defecto físico percibido). En el delirante somático la creencia es sobre ENFERMEDAD, defecto funcional o infestación."}
       ],
    quiz:[
       {p:"Paciente con TOC inicia sertralina 50 mg/día. A las 6 semanas refiere leve mejoría. ¿Conducta más apropiada?",
        o:["Cambiar a fluoxetina","Escalar a dosis altas (150–200 mg) y completar 10–12 semanas","Añadir clonazepam","Declarar refractario y pasar a clomipramina"],r:1,
        x:"TOC requiere dosis ALTAS (sertralina 150–200 mg en TOC vs 50–100 mg en depresión) y la respuesta completa tarda 10–12 semanas. No se cambia a las 6 semanas si hay mejoría; se escala la dosis y se espera."},
       {p:"¿Cuál es la psicoterapia de elección en TOC?",
        o:["TCC genérica","Exposición y Prevención de Respuesta (EPR)","Terapia psicodinámica","EMDR"],r:1,
        x:"EPR es el gold standard. Equivalente o superior a fármacos aislados; la combinación (ISRS + EPR) es lo óptimo."},
       {p:"Niño de 8 años previamente sano desarrolla SÚBITAMENTE rituales de lavado de manos 2 semanas después de faringitis estreptocócica. ¿Sospecha?",
        o:["TOC de inicio infantil clásico","PANDAS","Trastorno de adaptación","Encefalitis autoinmune anti-NMDA"],r:1,
        x:"PANDAS: TOC de inicio BRUSCO post-infección estreptocócica. Tratar la infección (antibiótico) + manejo estándar del TOC."},
       {p:"Varón de 22 años convencido de que su nariz es 'grotesca' (objetivamente normal). Pasa 4 h/día frente al espejo. Pide consulta con cirugía plástica. ¿Conducta?",
        o:["Derivarlo a cirugía plástica","Diagnosticar TDC · ISRS dosis altas + TCC · NO cirugía","Tranquilizarlo y alta","Iniciar antipsicótico por creencia delirante"],r:1,
        x:"TDC. La cirugía cosmética EMPEORA el cuadro. Tratamiento: ISRS dosis altas + TCC específica. Screening de suicidio obligatorio (riesgo ~4×)."},
       {p:"Paciente con TOC severo sin respuesta a 2 ISRS a dosis máximas ni a clomipramina. ¿Siguiente paso?",
        o:["Psicoterapia psicodinámica","Augmentación con risperidona 1–3 mg/día","BZD a dosis alta","Litio"],r:1,
        x:"Augmentación con antipsicótico atípico (risperidona o aripiprazol, este último si hay tics) es la 3ª línea. Refractarios verdaderos: EMT, ECT, DBS."},
       {p:"Mujer de 30 años se arranca pelos de cejas y pestañas desde hace 2 años, con alopecia visible. Refiere urgencia previa y alivio después. ¿Dx?",
        o:["TOC","Tricotilomanía","TDC","Trastorno de estereotipias motoras"],r:1,
        x:"Tricotilomanía. Tratamiento: Terapia de Reversión de Hábito (TRH) como primera línea. N-acetilcisteína 1200–2400 mg/d tiene evidencia. ISRS limitada."}
     ]
  },
  trauma:{
    meta:{name:"trauma",label:"Trauma",icon:"⚡",color:C.trm},
    flash:[
         {q:"¿Cuál es la duración mínima de síntomas para diagnosticar TEPT?",r:"≥1 mes desde el evento traumático. Si es de 3 días a 1 mes, el diagnóstico es trastorno de estrés agudo (TEA)."},
         {q:"¿Cuáles son los 4 grupos de síntomas del TEPT?",r:"B) Intrusión (≥1 de 5) — recuerdos, sueños, flashbacks, malestar ante claves, reacciones fisiológicas. C) Evitación (≥1 de 2). D) Alteraciones negativas de cognición/ánimo (≥2 de 7). E) Hiperactivación (≥2 de 6)."},
         {q:"¿Qué ISRS tienen aprobación FDA específica para TEPT?",r:"Sertralina y paroxetina. Son los únicos con indicación oficial. Venlafaxina XR es alternativa de primera línea."},
         {q:"¿Por qué están contraindicadas las BZD en TEPT?",r:"No tratan los síntomas nucleares, interfieren con el procesamiento del trauma en psicoterapia, empeoran la disociación y tienen alto riesgo de dependencia en esta población."},
         {q:"¿Para qué sirve la prazosina en TEPT y a qué dosis?",r:"Reduce pesadillas e hiperactivación nocturna. Antagonista α1-adrenérgico. Iniciar 1 mg nocturno, titular hasta 10 mg."},
         {q:"¿Qué es EMDR?",r:"Eye Movement Desensitization and Reprocessing. Psicoterapia basada en movimientos oculares bilaterales durante la evocación del recuerdo traumático. Eficacia equivalente a TCC centrada en trauma."},
         {q:"¿Cuál es la diferencia entre trastorno de adaptación y TEPT?",r:"El criterio A. TEPT requiere exposición a trauma estricto (muerte/lesión grave/violencia sexual). Adaptación: estresor identificable NO traumático (divorcio, desempleo, mudanza)."},
         {q:"¿Cuándo aparecen y resuelven los síntomas del trastorno de adaptación?",r:"Aparecen dentro de los 3 meses del estresor. Resuelven dentro de los 6 meses tras su cese (salvo que el estresor sea crónico)."},
         {q:"¿Cuál es la duración mínima para diagnosticar trastorno de duelo prolongado?",r:"≥12 meses tras la muerte en adultos. ≥6 meses en niños y adolescentes. Nuevo diagnóstico del DSM-5-TR (2022)."},
         {q:"¿En qué se diferencia el apego reactivo del desinhibido?",r:"Ambos por cuidado patogénico. Apego reactivo: niño INHIBIDO, no busca consuelo, no responde emocionalmente. Desinhibido: niño con conductas excesivamente familiares e indiscriminadas con adultos desconocidos."},
         {q:"¿Qué condiciones debe cumplir una muerte para contar como trauma en el criterio A?",r:"Si el paciente se enteró (no presenció), la muerte debe haber sido VIOLENTA O ACCIDENTAL. Una muerte esperada por cáncer, por ejemplo, no cumple criterio A."},
         {q:"¿Cuántos síntomas se necesitan para el TEA?",r:"≥9 síntomas de cualquier categoría (intrusión, ánimo negativo, disociación, evitación, activación), durante 3 días a 1 mes tras el trauma."},
         {q:"¿Cuál es la edad de presentación típica del trastorno de apego reactivo?",r:"Antes de los 5 años (criterio F). El niño debe tener edad de desarrollo ≥9 meses."},
         {q:"¿Qué especificador del TEPT se aplica si los criterios se cumplen tardíamente?",r:"Con expresión retardada: cuando los criterios completos no se cumplen hasta al menos 6 meses tras el evento traumático."}
       ],
    quiz:[
       {p:"Veterano de guerra con 3 meses de pesadillas sobre combate, evitación de multitudes, hipervigilancia y sueño fragmentado. ¿Fármaco ideal para las pesadillas?",
        o:["Diazepam 5 mg nocturno","Prazosina 1–10 mg nocturno","Quetiapina 100 mg","Zolpidem 10 mg"],r:1,
        x:"Prazosina (antagonista α1) reduce pesadillas e hiperactivación nocturna en TEPT. Las BZD están contraindicadas en TEPT."},
       {p:"Mujer 35 años, 2 meses tras accidente de tránsito grave: flashbacks, evita conducir, insomnio, hiperreactividad. TSH normal. ¿Dx y 1ª línea?",
        o:["TEA · BZD","TEPT · Sertralina + TCC-CT","Adaptación · apoyo","Trastorno de pánico · ISRS"],r:1,
        x:"Síntomas >1 mes + cumple criterio A (accidente con amenaza real) + 4 grupos de síntomas = TEPT. Sertralina (FDA) + TCC centrada en trauma."},
       {p:"Hombre 40 años, una semana tras robo con violencia: pesadillas, evitación, disociación, hiperreactividad. ¿Dx?",
        o:["TEPT","TEA (trastorno de estrés agudo)","Adaptación","Psicosis breve"],r:1,
        x:"Duración 3 días–1 mes tras trauma = TEA. Si persiste >1 mes pasa a TEPT."},
       {p:"Mujer divorciada hace 2 meses, ánimo bajo, llanto, irritabilidad, dificultad para funcionar. Sin antecedentes. ¿Dx más probable?",
        o:["TEPT","Depresión mayor","Trastorno de adaptación con ánimo deprimido","Duelo"],r:2,
        x:"Estresor NO traumático (divorcio) + síntomas <3 m tras inicio + no cumple otro trastorno = trastorno de adaptación. Subtipo con ánimo deprimido."},
       {p:"Mujer de 58 años, 14 meses tras muerte de esposo. Anhelo intenso persistente, evita cosas que lo recuerden, siente que la vida no tiene sentido, no ha podido volver a trabajar. ¿Dx?",
        o:["Duelo normal","Depresión mayor","Trastorno de duelo prolongado","TEPT"],r:2,
        x:"Duración ≥12 meses + anhelo persistente + ≥3 síntomas adicionales + deterioro = trastorno de duelo prolongado (DSM-5-TR). La depresión mayor tendría más autodevaluación no relacionada con la pérdida."},
       {p:"Niño de 4 años criado en orfanato hasta los 2 años. Adoptado hace 2. Muy retraído, no busca consuelo cuando se lastima, poca respuesta emocional, respuestas irritables aisladas. ¿Dx?",
        o:["TEA (autismo)","Trastorno de apego reactivo","Trastorno de relación social desinhibida","Trastorno de adaptación"],r:1,
        x:"Patrón inhibido + antecedente de cuidado patogénico (institución) + edad <5 años = trastorno de apego reactivo. El autismo tendría déficits sociales independientes del cuidado y comportamientos restringidos/repetitivos."}
     ]
  },
  somaticos:{
    meta:{name:"somaticos",label:"Somáticos",icon:"🧬",color:C.som},
    flash:[
         {q:"¿Cuál es la diferencia entre TSS e IAD?",r:"TSS: síntomas físicos REALES y angustiantes + respuesta psicológica desproporcionada. IAD (hipocondría): preocupación por enfermar con síntomas físicos AUSENTES o LEVES."},
         {q:"¿Qué es el signo de Hoover y qué indica?",r:"En una 'parálisis' conversiva de pierna: al pedir al paciente levantar la pierna SANA, se detecta contracción involuntaria (extensión) en la 'parética'. Es un signo POSITIVO de conversión (incompatibilidad con lesión)."},
         {q:"¿Cuál es la diferencia entre trastorno facticio y simulación?",r:"Ambos producen síntomas conscientemente. Facticio: motivación INTERNA (asumir rol de enfermo). Simulación: motivación EXTERNA (dinero, licencia, droga, evadir). Simulación no es trastorno mental."},
         {q:"¿Qué diferencia hay entre conversión, facticio y simulación?",r:"Conversión: síntomas INVOLUNTARIOS, el paciente no es consciente de producirlos. Facticio: CONSCIENTE, motivación interna. Simulación: CONSCIENTE, motivación externa clara."},
         {q:"¿Qué es el trastorno facticio impuesto a otro?",r:"Antes llamado Munchausen por poderes. Un cuidador produce o induce síntomas en un tercero (típicamente hijo). Es una forma de MALTRATO INFANTIL. Requiere protección del menor."},
         {q:"¿Cuál es la duración mínima para diagnosticar IAD?",r:"≥6 meses de preocupación por tener o adquirir una enfermedad grave."},
         {q:"¿Cuáles son los 3 tipos de amnesia disociativa?",r:"Localizada (más común: pérdida de un evento o periodo), selectiva (recuerdo parcial del evento) y generalizada (rara, pérdida total de memoria autobiográfica)."},
         {q:"¿Cómo se diferencia amnesia disociativa de amnesia orgánica (Korsakoff, TCE)?",r:"Disociativa: sin alteración de conciencia, sin confabulación, información RECUPERABLE con el tiempo. Orgánica: déficit de tiamina (Korsakoff), confabulación, déficits cognitivos asociados."},
         {q:"¿Qué es la fuga disociativa?",r:"Especificador de la amnesia disociativa: viaje o deambulación aparentemente intencionada + amnesia de identidad u otra información autobiográfica. El paciente puede asumir una nueva identidad temporal."},
         {q:"¿Cuál es el criterio clave del trastorno de despersonalización / desrealización?",r:"La prueba de realidad permanece INTACTA. El paciente sabe que es una sensación, no una realidad. Es el rasgo que distingue de la psicosis."},
         {q:"¿Cuál es el tratamiento base del TID?",r:"Psicoterapia trauma-informada en 3 fases: estabilización → procesamiento del trauma → integración. NO hay fármaco con indicación específica. ISRS para depresión/ansiedad, prazosina para pesadillas."},
         {q:"¿Por qué se debe evitar BZD en pacientes disociativos?",r:"Pueden empeorar la disociación y tienen alto riesgo de dependencia en esta población (alta comorbilidad con TEPT y uso de sustancias)."},
         {q:"¿Qué porcentaje de adultos sanos ha experimentado despersonalización transitoria?",r:"Aproximadamente 50%, especialmente en contextos de fatiga, estrés agudo, alcohol o cannabis. Solo es trastorno cuando es persistente/recurrente y causa malestar o deterioro."},
         {q:"¿Por qué se renombró 'histeria' a 'trastorno de conversión'?",r:"Porque 'histeria' era un término estigmatizante y culturalmente cargado. El DSM-5 lo renombró 'síntomas neurológicos funcionales' y el diagnóstico ahora se basa en signos positivos de incompatibilidad con lesión, no en la búsqueda de conflicto psicológico."}
       ],
    quiz:[
       {p:"Mujer 40 años, 3 años de múltiples síntomas (dolor abdominal, cefalea, fatiga, parestesias). Consulta a 8 médicos, exige exámenes. Síntomas reales pero pruebas normales o benignas. ¿Dx?",
        o:["Simulación","TSS (trastorno de síntomas somáticos)","IAD (ansiedad por enfermedad)","Facticio"],r:1,
        x:"Síntomas físicos reales + tiempo/energía/pensamientos excesivos + ≥6 meses = TSS. En IAD no habría síntomas físicos marcados."},
       {p:"Varón 30 años sin síntomas físicos relevantes, convencido de tener cáncer. Se palpa constantemente, se hace múltiples TAC. Pruebas normales. ¿Dx?",
        o:["TSS","Trastorno de ansiedad por enfermedad (IAD)","Trastorno delirante somático","TOC"],r:1,
        x:"Preocupación por enfermar con síntomas ausentes o leves + alta ansiedad + comportamientos excesivos + ≥6 meses = IAD. Reemplazó a 'hipocondría' en DSM-5."},
       {p:"Mujer 25 años con parálisis aguda de pierna tras discusión familiar. Al pedirle levantar la pierna sana, la 'parética' hace extensión. EMG normal. ¿Dx?",
        o:["ACV","Síndrome de Guillain-Barré","Trastorno de conversión","Simulación"],r:2,
        x:"Signo de Hoover positivo = incompatibilidad con lesión anatómica = conversión. No es simulación porque no hay ganancia externa identificable."},
       {p:"Enfermera de 35 años con múltiples hospitalizaciones por síntomas autoinducidos (inyectarse insulina sin ser diabética). No hay ganancia externa. ¿Dx?",
        o:["Trastorno de conversión","Trastorno facticio","Simulación","Síndrome de Cotard"],r:1,
        x:"Producción INTENCIONAL de síntomas + motivación INTERNA (rol de enfermo) + sin ganancia externa = facticio. Clásica presentación (Munchausen)."},
       {p:"Varón 28 años reporta no recordar los últimos 3 meses tras suicidio de su hermano. Conservado, orientado, sin lesión ni tóxicos. ¿Dx?",
        o:["Amnesia por TCE","Amnesia disociativa localizada","Demencia","Korsakoff"],r:1,
        x:"Fallo para recordar un periodo específico asociado a trauma/estrés, sin alteración de conciencia, sin lesión = amnesia disociativa localizada (la más común)."},
       {p:"¿Cuál es el tratamiento base del TID?",
        o:["Clozapina","Psicoterapia trauma-informada en 3 fases","ECT","Haloperidol"],r:1,
        x:"Psicoterapia trauma-informada (estabilización → procesamiento → integración). No hay fármaco específico. ISRS para comorbilidades, prazosina para pesadillas."}
     ]
  },
  tca:{
    meta:{name:"tca",label:"TCA",icon:"🍽️",color:C.tca},
    flash:[
         {q:"¿Cuál es el TCA con la mortalidad más alta de todos los trastornos psiquiátricos?",r:"Anorexia nerviosa. Mortalidad ~5–10% a 10 años. Causa: arritmias, desnutrición y suicidio."},
         {q:"¿Cuáles son los 2 subtipos de anorexia nerviosa?",r:"Restrictivo (sin atracones/purgas en 3 meses) y con atracones/purgas (vómito, laxantes, diuréticos, enemas en 3 meses)."},
         {q:"¿Qué es el signo de Russell y en qué cuadro aparece?",r:"Callosidades en el dorso de los nudillos por el contacto repetido con los dientes al inducir el vómito. Aparece en bulimia y en anorexia subtipo con purgas."},
         {q:"¿Cuál es la frecuencia mínima de atracones para diagnosticar bulimia?",r:"≥1 atracón + conducta compensatoria por semana durante al menos 3 meses. Misma frecuencia para trastorno por atracón (sin conducta compensatoria)."},
         {q:"¿Cuál es la dosis de fluoxetina para bulimia nerviosa y por qué es especial?",r:"60 mg/día. Es el ÚNICO ISRS con aprobación FDA específica para bulimia. Dosis MAYOR que en depresión (20 mg)."},
         {q:"¿Qué fármaco tiene aprobación FDA específica para el trastorno por atracón y a qué dosis?",r:"Lisdexanfetamina 50–70 mg/día en adultos. Único aprobado específicamente."},
         {q:"¿Por qué está contraindicado el bupropión en anorexia y bulimia?",r:"Reduce el umbral convulsivo. En pacientes con alteraciones electrolíticas por purgas, el riesgo de convulsiones aumenta significativamente."},
         {q:"¿Qué es el síndrome de realimentación y cómo se previene?",r:"Complicación al iniciar nutrición en paciente muy desnutrido: la insulina desplaza fosfato, potasio y magnesio al intracelular → arritmias, ICC, edema pulmonar. Prevención: tiamina 100–200 mg IV previa, iniciar a 20 kcal/kg/día, suplementar electrolitos, monitoreo diario de electrolitos x 7 días."},
         {q:"¿Cuáles son los umbrales de IMC para la gravedad de la anorexia en adultos?",r:"Leve ≥17 · Moderada 16–16.99 · Grave 15–15.99 · Extrema <15 kg/m²."},
         {q:"¿Qué diferencia ARFID de anorexia nerviosa?",r:"ARFID tiene evitación/restricción alimentaria SIN preocupación por la imagen corporal ni miedo a engordar. Comparte el bajo peso pero no la psicopatología central de la anorexia."},
         {q:"¿Qué diagnóstico se debe sospechar en una persona que come hielo compulsivamente?",r:"Pagofagia — fuertemente asociada a anemia ferropénica. Medir ferritina y hemograma. Suele mejorar al corregir el déficit de hierro."},
         {q:"¿Cuál es la psicoterapia de primera línea para anorexia nerviosa en adolescentes?",r:"Terapia familiar basada en Maudsley (TFB-M). Los padres son los 'agentes del cambio' al inicio del tratamiento, encargados de la realimentación."},
         {q:"¿Qué trastornos electrolítico-ácido-base son típicos del vómito autoinducido?",r:"Alcalosis metabólica hipoclorémica, con hipocalemia. Pérdida de HCl por el vómito."},
         {q:"¿Qué trastorno ácido-base es típico del abuso de laxantes?",r:"Acidosis metabólica hiperclorémica (pérdida de bicarbonato intestinal). También hipocalemia por pérdida de K+ en heces."}
       ],
    quiz:[
       {p:"Adolescente de 16 años, IMC 16 kg/m², amenorrea, lanugo, bradicardia, hipotensión. Restringe la comida, hace ejercicio 3 h/día, se ve 'gorda'. ¿Dx y terapia de 1ª línea?",
        o:["Anorexia nerviosa restrictiva · TCC individual","Anorexia nerviosa restrictiva · TFB-Maudsley","Bulimia nerviosa · fluoxetina 60 mg","ARFID · exposición gradual"],r:1,
        x:"AN restrictiva en adolescente. 1ª línea: Terapia Familiar Basada en Maudsley (TFB-M). Los padres actúan como agentes del cambio en la realimentación."},
       {p:"Mujer 22 años, peso normal (IMC 23), atracones 3 veces/sem + vómito autoprovocado x 5 meses. Callosidades en nudillos, erosión dental. K+ 2.8 mEq/L. ¿Dx y fármaco de 1ª línea?",
        o:["Anorexia nerviosa con purgas · olanzapina","Bulimia nerviosa · fluoxetina 60 mg","Trastorno por atracón · lisdexanfetamina","Rumiación · biofeedback"],r:1,
        x:"Peso normal + atracones + purgas ≥1 sem x 3 meses = BN. Signo de Russell + erosión dental. Fluoxetina 60 mg es el ÚNICO ISRS con aprobación FDA para BN. Corregir hipocalemia es prioridad aguda."},
       {p:"Hombre 35 años, IMC 35, atracones 2 veces/sem x 6 meses sin conductas compensatorias, gran culpa tras comer. ¿Fármaco de 1ª línea?",
        o:["Sertralina 100 mg","Lisdexanfetamina 50–70 mg","Fluoxetina 60 mg","Bupropión 300 mg"],r:1,
        x:"Trastorno por atracón. Lisdexanfetamina es el único fármaco con aprobación FDA específica para TpA. Bupropión NUNCA en cuadros con purgas o restricciones."},
       {p:"Paciente con AN severa (IMC 13) inicia realimentación. A las 48 h aparece edema, taquicardia, debilidad. P 1.2 mg/dL, K+ 2.5. ¿Qué pasó?",
        o:["Sepsis","Síndrome de realimentación","Hipertiroidismo","Pancreatitis"],r:1,
        x:"Clásico síndrome de realimentación: insulina ↑ desplaza P, K, Mg al intracelular → hipofosfatemia, hipocalemia, riesgo de arritmias e ICC. Prevenir con 20 kcal/kg/día inicial + tiamina + suplementos electrolíticos + monitoreo diario."},
       {p:"Niño de 5 años con espectro autista que solo acepta 4 alimentos específicos, vomita con otros por su textura. Pérdida de peso. No le preocupa su imagen corporal. ¿Dx?",
        o:["Anorexia infantil","ARFID","Pica","Rumiación"],r:1,
        x:"ARFID subtipo sensorial: evitación basada en textura/olor/sabor, sin distorsión de imagen corporal. Muy frecuente en niños con espectro autista."},
       {p:"Mujer embarazada con anemia ferropénica refiere comer hielo compulsivamente. ¿Dx y manejo?",
        o:["Pica · corregir deficiencia de hierro","Bulimia · fluoxetina","TOC · ISRS","Trastorno delirante · antipsicótico"],r:0,
        x:"Pagofagia (comer hielo) es una forma de pica fuertemente asociada a ferropenia. Suele resolver con la corrección del déficit de hierro."}
     ]
  },
  sueno:{
    meta:{name:"sueno",label:"Sueño",icon:"🌙",color:C.sue},
    flash:[
         {q:"¿Cuál es el tratamiento de primera línea del trastorno de insomnio?",r:"Terapia cognitivo-conductual para el insomnio (TCC-I). Superior o equivalente a fármacos a largo plazo. Incluye higiene del sueño, control de estímulos, restricción de sueño y reestructuración cognitiva."},
         {q:"¿Cuáles son los componentes de la tétrada clásica de narcolepsia?",r:"1) Ataques de sueño, 2) cataplejía (pérdida súbita bilateral del tono muscular desencadenada por emoción), 3) alucinaciones hipnagógicas/hipnopómpicas, 4) parálisis del sueño."},
         {q:"¿Cuál es el gold standard de tratamiento para la cataplejía en narcolepsia?",r:"Oxibato de sodio. Alternativas: pitolisant, venlafaxina, atomoxetina, clomipramina."},
         {q:"¿Cuál es el neurotransmisor deficiente en narcolepsia tipo 1 y la asociación HLA?",r:"Deficiencia de orexina (hipocretina) por pérdida autoinmune de neuronas hipotalámicas. Asociación con HLA-DQB1*06:02. Hipocretina en LCR disminuida o indetectable."},
         {q:"¿Cuál es el tratamiento de 1ª línea para la apnea obstructiva del sueño moderada-grave?",r:"CPAP nasal. Gold standard. Reduce somnolencia, HTA y eventos cardiovasculares."},
         {q:"¿Por qué se deben evitar BZD y opioides en AOS?",r:"Deprimen la ventilación y empeoran las apneas. Son contraindicación relativa."},
         {q:"¿Qué parámetro de laboratorio es clave investigar en el síndrome de piernas inquietas?",r:"Ferritina. Si es <75 ng/mL, suplementar con hierro oral o IV mejora significativamente el cuadro."},
         {q:"¿Qué es el fenómeno de aumentación en SPI?",r:"Efecto paradójico de los agonistas dopaminérgicos: con el tiempo, el tratamiento empeora el SPI (síntomas aparecen antes, son más intensos, se extienden a otras partes del cuerpo). Por eso gabapentinoides son ahora 1ª línea farmacológica."},
         {q:"¿En qué fase del sueño y momento de la noche ocurren las parasomnias NREM?",r:"En sueño N3 (ondas lentas), en la PRIMERA mitad de la noche. Ejemplos: sonambulismo y terror nocturno. Hay amnesia del episodio."},
         {q:"¿En qué fase del sueño y momento ocurren las pesadillas?",r:"En sueño REM, en la SEGUNDA mitad de la noche. El paciente despierta completamente orientado y recuerda el sueño con detalle."},
         {q:"¿Cómo diferencias un terror nocturno de una pesadilla?",r:"Terror nocturno: N3, 1ª mitad, amnesia, sin relato del sueño. Pesadilla: REM, 2ª mitad, recuerdo vívido del sueño, despertar orientado."},
         {q:"¿Cuál es el tratamiento de 1ª línea para pesadillas, especialmente si hay TEPT comórbido?",r:"Terapia de ensayo por imágenes (IRT). En TEPT: prazosina 1–10 mg nocturnos, antagonista α1-adrenérgico."},
         {q:"¿Qué enfermedades neurodegenerativas predice el trastorno de conducta del sueño REM (TCSR)?",r:"Sinucleinopatías: Parkinson, demencia con cuerpos de Lewy, atrofia multisistémica. ~80% desarrolla una en 10–15 años."},
         {q:"¿Cuál es el tratamiento de 1ª línea del TCSR?",r:"Clonazepam 0.25–2 mg nocturno o melatonina 3–12 mg nocturno (preferida en adultos mayores). Seguridad del entorno es clave."},
         {q:"¿Cuál es el manejo del jet-lag?",r:"Melatonina 0.5–3 mg al horario de destino + fototerapia. Ajuste gradual en viajes largos."}
       ],
    quiz:[
       {p:"Mujer 38 años, 5 meses con dificultad para conciliar el sueño y despertares nocturnos, 4 noches/semana. Fatiga diurna. TSH normal. ¿Tratamiento 1ª línea?",
        o:["Zolpidem 10 mg nocturno crónico","TCC para insomnio","Clonazepam 1 mg","Quetiapina 25 mg"],r:1,
        x:"TCC-I es 1ª línea para trastorno de insomnio. Superior o equivalente a fármacos a largo plazo y sin los riesgos de dependencia. Los fármacos son puente corto."},
       {p:"Hombre 22 años con ataques irresistibles de sueño durante el día, con episodios de debilidad al reírse. ¿Dx y manejo cataplejía?",
        o:["Hipersomnia · modafinilo","Narcolepsia · oxibato de sodio para cataplejía","AOS · CPAP","TCSR · clonazepam"],r:1,
        x:"Narcolepsia tipo 1 con cataplejía. Oxibato de sodio es el gold standard para cataplejía. Modafinilo para la somnolencia diurna."},
       {p:"Hombre 55 años, obeso, con ronquidos fuertes y pausas respiratorias presenciadas, somnolencia diurna (Epworth 15). PSG: IAH 28. ¿Manejo?",
        o:["Zolpidem nocturno","CPAP nasal + pérdida de peso","Modafinilo solo","Agonistas dopaminérgicos"],r:1,
        x:"AOS moderada-grave. CPAP es gold standard. Asociar pérdida de peso y evitar alcohol y BZD (deprimen ventilación)."},
       {p:"Mujer 60 años refiere urgencia de mover piernas con hormigueo, peor de noche, mejora con movimiento. Ferritina 45 ng/mL. ¿Primer paso?",
        o:["Pramipexol","Suplementación con hierro","Gabapentina enacarbil","Clonazepam"],r:1,
        x:"SPI + ferritina <75 ng/mL → suplementación con hierro es primer paso. Si persiste con ferritina corregida, gabapentinoides son 1ª línea farmacológica (evitar aumentación de agonistas dopa)."},
       {p:"Niño de 7 años con episodios 2h tras dormirse: se sienta, grita, suda, no responde a padres, no recuerda al día siguiente. ¿Dx?",
        o:["Pesadillas","Terror nocturno","Epilepsia nocturna","Narcolepsia"],r:1,
        x:"Terror nocturno: parasomnia NREM (N3) en 1ª mitad de la noche, con amnesia del episodio. Diferente de pesadilla (REM, 2ª mitad, con recuerdo)."},
       {p:"Hombre 65 años grita y patea durante el sueño, le pega a su esposa. Recuerda sueños de persecución. ¿Dx y riesgo futuro?",
        o:["Sonambulismo · bajo riesgo","TCSR · alto riesgo de Parkinson/DLB","Terror nocturno · benigno","SPI · neuropatía"],r:1,
        x:"TCSR: actúa sueños durante REM por pérdida de atonía. ~80% desarrolla sinucleinopatía (Parkinson, DLB, MSA) en 10–15 años. Tratar con clonazepam o melatonina + seguimiento neurológico."}
     ]
  },
  personalidad:{
    meta:{name:"personalidad",label:"Personalidad",icon:"🎭",color:C.per},
    flash:[
         {q:"¿Cuáles son los 3 clusters de trastornos de personalidad?",r:"A (raros/excéntricos): paranoide, esquizoide, esquizotípica. B (dramáticos/emocionales): antisocial, límite, histriónica, narcisista. C (ansiosos/temerosos): evitativa, dependiente, obsesivo-compulsiva."},
         {q:"¿Cuál es el tratamiento de primera línea para el trastorno límite de personalidad?",r:"DBT (terapia dialéctica conductual) de Marsha Linehan. Incluye: mindfulness, regulación emocional, tolerancia al malestar y efectividad interpersonal."},
         {q:"¿Cuál es la diferencia entre TOCP y TOC?",r:"TOCP: rasgo de personalidad EGO-SINTÓNICO (la persona cree que su perfeccionismo es correcto y bueno). TOC: obsesiones y compulsiones EGO-DISTÓNICAS (la persona sabe que son absurdas y quiere librarse)."},
         {q:"¿Qué antecedente es necesario para diagnosticar trastorno antisocial de personalidad?",r:"Evidencia de trastorno de la conducta antes de los 15 años. Sin este antecedente, no puede diagnosticarse. Además, el paciente debe tener ≥18 años."},
         {q:"¿Cómo se diferencia el trastorno esquizoide del esquizotípico?",r:"Esquizoide: desapego e indiferencia, prefiere la soledad. Esquizotípica: además, tiene distorsiones cognitivas/perceptivas y excentricidad (pensamiento mágico, ideas de referencia)."},
         {q:"¿Cómo se diferencia el trastorno evitativo del esquizoide?",r:"Evitativa: DESEA relaciones pero las evita por miedo al rechazo. Esquizoide: NO DESEA relaciones, prefiere estar solo."},
         {q:"¿Qué es la 'escisión' en el TLP?",r:"Mecanismo defensivo nuclear del TLP: alternancia entre idealización ('eres perfecto') y devaluación ('eres horrible') del mismo objeto. Genera relaciones interpersonales inestables e intensas."},
         {q:"¿Cuáles son los 9 criterios del TLP (DSM-5)?",r:"1) Esfuerzos por evitar abandono, 2) relaciones inestables con escisión, 3) alteración de identidad, 4) impulsividad en ≥2 áreas, 5) conductas suicidas/autolesivas, 6) inestabilidad afectiva, 7) vacío crónico, 8) ira intensa, 9) ideación paranoide o disociación transitorias. Se requieren ≥5 de 9."},
         {q:"¿Cuál es la tasa de suicidio consumado en el TLP?",r:"Aproximadamente 10%. Alto riesgo — el screening suicida y el manejo de crisis son claves."},
         {q:"¿Qué porcentaje de pacientes con TLP tiene antecedentes de trauma infantil?",r:"Aproximadamente 70%. Abuso sexual, físico o negligencia. No es 'causa única' pero es factor de riesgo central."},
         {q:"¿Qué fármacos se pueden usar sintomáticamente en TLP?",r:"Estabilizadores (lamotrigina, valproato) para inestabilidad afectiva e impulsividad. Antipsicóticos atípicos bajos (aripiprazol, quetiapina) para ideación paranoide y agresividad. ISRS para depresión comórbida. EVITAR BZD (desinhibición + adicción)."},
         {q:"¿Cuál es el núcleo del trastorno narcisista de personalidad?",r:"Grandiosidad + necesidad de admiración + falta de empatía. Sentido de privilegio, explotación interpersonal, arrogancia."},
         {q:"¿Qué caracteriza al trastorno histriónico de personalidad?",r:"Emotividad excesiva y búsqueda de atención. Necesita ser el centro. Comportamiento seductor, expresión emocional superficial y cambiante, sugestionabilidad."},
         {q:"¿Qué caracteriza al trastorno dependiente de personalidad?",r:"Necesidad excesiva de ser cuidado, conducta sumisa y pegadiza, miedo a la separación. Dificultad para tomar decisiones sin tranquilización, dificultad para estar solo, busca urgentemente una nueva relación cuando una termina."},
         {q:"¿Por qué un cambio súbito de personalidad en un adulto debe alertar sobre causa orgánica?",r:"Los trastornos de personalidad inician en adolescencia o adultez temprana y son estables. Un cambio abrupto en adulto sugiere causa orgánica: tumor frontal, demencia, infección del SNC, enfermedad médica o sustancia."}
       ],
    quiz:[
       {p:"Mujer 24 años con múltiples relaciones intensas que duran semanas, alterna entre idealizar y odiar a sus parejas, autolesiones superficiales repetidas, impulsividad en compras y sexo, sensación crónica de vacío. ¿Dx y terapia 1ª línea?",
        o:["Bipolar II · litio","TLP · DBT","Histriónica · TCC","Depresión mayor · ISRS"],r:1,
        x:"TLP clásico: escisión, autolesiones, impulsividad, vacío crónico. DBT (Linehan) es terapia de elección. Diferenciar de bipolar II por la inestabilidad afectiva de horas (reactiva) vs episodios de días-semanas."},
       {p:"Hombre 32 años con múltiples arrestos, no mantiene trabajo, miente sistemáticamente, sin remordimiento. Antecedente de vandalismo y conductas agresivas desde los 12 años. ¿Dx?",
        o:["Trastorno explosivo intermitente","Trastorno antisocial de personalidad","Trastorno narcisista","Trastorno límite"],r:1,
        x:"Transgresión persistente de derechos ajenos + antecedente de trastorno de conducta antes de los 15 años + edad ≥18 = antisocial. Sin el antecedente antes de los 15, no se diagnostica."},
       {p:"Varón 45 años, ingeniero, muy perfeccionista, trabaja 70h/semana, no delega, guarda todo, rígido moralmente. CREE que es lo correcto y necesario. No hay obsesiones ni compulsiones específicas. ¿Dx?",
        o:["TOC","TOCP (trastorno obsesivo-compulsivo de personalidad)","Narcisista","Ansiedad generalizada"],r:1,
        x:"TOCP: rasgo de personalidad ego-sintónico de perfeccionismo y rigidez. Sin obsesiones ni compulsiones específicas. El paciente cree que su forma de ser es correcta (a diferencia del TOC donde la persona sabe que sus síntomas son absurdos)."},
       {p:"Mujer 28 años con sentimientos persistentes de inadecuación, muy tímida, rechaza trabajos con trato a público, desea relaciones pero no las inicia por miedo al rechazo. ¿Dx más probable?",
        o:["Fobia social","Esquizoide","Evitativa","TAG"],r:2,
        x:"Patrón pervasivo de inhibición social + sentimientos de inadecuación + DESEA relaciones pero evita por miedo al rechazo = evitativa. Diferencia con esquizoide (no desea) y fobia social (puede ser más circunscrita)."},
       {p:"Hombre 50 años con desconfianza generalizada, cree que colegas le conspiran, guarda rencores, hipersensible a la crítica. NO hay delirios fijos ni alucinaciones. Funciona en el trabajo pero es conflictivo. ¿Dx?",
        o:["Trastorno delirante persecutorio","Personalidad paranoide","Esquizofrenia paranoide","Personalidad esquizotípica"],r:1,
        x:"Desconfianza y suspicacia pervasivas SIN delirios fijos ni alucinaciones = personalidad paranoide. El trastorno delirante requiere creencia delirante específica ≥1 mes. La esquizofrenia requiere síntomas positivos."},
       {p:"Paciente con TLP severo. Se considera añadir fármaco sintomático. Presenta alta impulsividad e inestabilidad afectiva. ¿Mejor opción?",
        o:["BZD crónica","Lamotrigina o valproato","Paroxetina a dosis altas","Olanzapina 20 mg"],r:1,
        x:"Estabilizadores del ánimo (lamotrigina, valproato) tienen mejor evidencia para impulsividad e inestabilidad afectiva en TLP. BZD CONTRAINDICADA por desinhibición y adicción. Antipsicóticos para ideación paranoide o agresividad marcada."}
     ]
  },
  impulsos:{
    meta:{name:"impulsos",label:"Impulsos",icon:"🎯",color:C.imp},
    flash:[
         {q:"¿Qué antecedente se necesita para diagnosticar trastorno antisocial en un adulto?",r:"Evidencia de trastorno de la conducta antes de los 15 años. Sin este antecedente, no se diagnostica antisocial en ≥18 años."},
         {q:"¿Cuáles son las 4 categorías de síntomas del trastorno de la conducta?",r:"1) Agresión a personas/animales, 2) destrucción de propiedad, 3) engaño o robo, 4) violaciones graves de normas. Se requieren ≥3 síntomas en últimos 12 meses, ≥1 en últimos 6."},
         {q:"¿Cómo se diferencia el trastorno negativista desafiante del trastorno de la conducta?",r:"Negativista: enfado, desafío, vengatividad — sin violación grave de derechos. Conducta: agresión, destrucción, robo, violaciones graves de normas sociales."},
         {q:"¿Cuáles son los dos patrones (A1 y A2) del trastorno explosivo intermitente?",r:"A1: Arrebatos de baja intensidad (verbales o físicos sin daño) ≥2 veces/semana × ≥3 meses. A2: Arrebatos de alta intensidad (daño a propiedad o lesión física) ≥3 en últimos 12 meses. Basta uno."},
         {q:"¿Cuáles son los criterios de piromanía?",r:"A) Incendios deliberados ≥1 ocasión. B) Tensión previa. C) Fascinación/atracción por el fuego. D) Placer al prenderlo o presenciarlo. E) NO por motivación económica/vengativa/ideológica/ocultar delito/respuesta a delirio. F) No explicado por CC, manía o antisocial."},
         {q:"¿Qué caracteriza a la cleptomanía?",r:"Impulso recurrente de robar objetos que NO son necesarios para uso personal ni por valor económico. Tensión previa + placer/alivio al robar. No es por rabia, venganza, delirios. ~3:1 mujeres."},
         {q:"¿Cuál es el tratamiento de 1ª línea del trastorno negativista desafiante?",r:"Parent Management Training (PMT) — terapia conductual con los padres, que aprenden reforzamiento positivo, consecuencias consistentes y manejo de límites. Terapia familiar. Tratar comorbilidades (TDAH muy frecuente)."},
         {q:"¿Qué fármacos tienen evidencia en trastorno explosivo intermitente?",r:"ISRS (fluoxetina con mejor evidencia). Estabilizadores del ánimo (valproato, litio). Antipsicóticos atípicos en casos graves. TCC con manejo de ira es 1ª línea."},
         {q:"¿Qué es el especificador 'con emociones prosociales limitadas' (callous-unemotional)?",r:"Especificador del trastorno de la conducta: rasgos de falta de remordimiento, poca empatía, afecto superficial, despreocupación por el rendimiento. Predice peor pronóstico y mayor riesgo de antisocial adulto."},
         {q:"¿Por qué un robo motivado por necesidad económica no es cleptomanía?",r:"La cleptomanía requiere que los objetos robados NO sean necesarios ni tengan valor económico para el paciente. Si hay motivación económica, es robo común (no trastorno mental)."},
         {q:"¿Qué fármacos pueden ayudar en cleptomanía?",r:"ISRS (fluoxetina) y naltrexona (antagonista opioide que modula sistema de recompensa). Ambos con evidencia moderada. TCC con desensibilización encubierta es 1ª línea."},
         {q:"¿Cuál es la comorbilidad más frecuente del trastorno negativista desafiante?",r:"TDAH (alrededor del 40%). Tratar el TDAH con estimulantes frecuentemente mejora también el negativismo."}
       ],
    quiz:[
       {p:"Niño de 9 años que pierde la calma fácilmente, discute con maestros y padres, se molesta deliberadamente a sus hermanos. No hay agresión física, no hay robos. Desde hace 8 meses. ¿Dx?",
        o:["Trastorno de la conducta","Trastorno negativista desafiante","TDAH","Trastorno explosivo intermitente"],r:1,
        x:"Patrón de enfado/desafío ≥6 meses sin violación grave de derechos = negativista desafiante. Conducta requiere agresión, destrucción, robo o violaciones graves."},
       {p:"Varón de 19 años con arrebatos explosivos con daño a propiedad varias veces al año, desproporcionados al estímulo, sin planeación, se arrepiente después. No patrón antisocial. ¿Dx?",
        o:["Trastorno antisocial","TEI (trastorno explosivo intermitente)","Trastorno bipolar","Conducta"],r:1,
        x:"Arrebatos IMPULSIVOS y desproporcionados (patrón A2: ≥3 con daño en 12m) sin premeditación ni patrón pervasivo = TEI. Antisocial tiene conducta planeada y sin remordimiento."},
       {p:"Niño de 14 años: peleas, robó en tiendas 3 veces, mintió repetidamente, incendió basurero, escaparse de casa. Inicio hace 2 años. ¿Dx?",
        o:["Trastorno negativista","Trastorno de la conducta","Antisocial (está en tiempo)","Trastorno bipolar I"],r:1,
        x:"≥3 síntomas de las 4 categorías (agresión, destrucción, engaño/robo, violaciones graves) en ≥12 meses en menor de 18 años = trastorno de la conducta. Antisocial solo se diagnostica ≥18 años con CC previo."},
       {p:"Mujer 30 años con múltiples episodios de robar cosmética que no necesita (los regala después). Sensación de tensión previa + alivio al robarlos. Sin antisocial ni manía. ¿Dx y tratamiento?",
        o:["Antisocial · no hay manejo","Cleptomanía · TCC + ISRS/naltrexona","TEI · fluoxetina","Trastorno de la conducta · terapia multisistémica"],r:1,
        x:"Robo impulsivo de objetos sin valor para el paciente + tensión/alivio + sin motivación económica/rabia = cleptomanía. TCC con desensibilización + ISRS o naltrexona."},
       {p:"Varón de 16 años incendia escuela tras reprobar. Se benefició (no tuvo que dar examen). ¿Dx?",
        o:["Piromanía","Trastorno de la conducta","TEI","Antisocial (edad)"],r:1,
        x:"Incendio con motivación instrumental (evadir examen) = NO piromanía. Entra en trastorno de la conducta (destrucción de propiedad). Piromanía requiere fascinación pura por el fuego, sin motivación instrumental."},
       {p:"Paciente con TEI severo sin respuesta inicial a TCC. ¿Opción farmacológica con mejor evidencia?",
        o:["BZD diaria","Fluoxetina","Quetiapina sola","Paroxetina a dosis bajas"],r:1,
        x:"Fluoxetina (ISRS) tiene la mejor evidencia en TEI. Valproato y litio como estabilizadores también son opciones. Antipsicóticos atípicos en casos muy graves."}
     ]
  },
  depresivos:{
    meta:{name:"depresivos",label:"Depresivos",icon:"💧",color:C.dpr},
    flash:[
         {q:"¿Cuál es la duración mínima de síntomas para diagnosticar un episodio depresivo mayor?",r:"Dos semanas con ≥5 de 9 síntomas, al menos uno siendo ánimo depresivo o anhedonia."},
         {q:"¿Qué significa la nemotecnia SIGECAPS?",r:"Los 9 síntomas del TDM: Sleep (sueño), Interest (interés/anhedonia), Guilt (culpa), Energy (energía), Concentration (concentración), Appetite (apetito), Psychomotor (psicomotor), Suicide (ideación suicida), más el ánimo bajo como ancla."},
         {q:"¿Cuál es el tratamiento de 1ª línea farmacológico del TDM?",r:"ISRS (sertralina, escitalopram, fluoxetina) + psicoterapia (TCC o TIP). Si falla: optimizar dosis, cambiar a otro ISRS/IRSN o atípico, aumentar (litio, T3, antipsicótico atípico)."},
         {q:"¿Cuánto tarda un ISRS en hacer efecto?",r:"Respuesta inicial en 2–4 semanas, efecto completo en 6–8 semanas. No cambiar antes de 4–6 semanas."},
         {q:"¿Cuánto debe durar el tratamiento antidepresivo tras la remisión?",r:"Primer episodio: 6–9 meses tras remisión. Dos o más episodios o episodio grave/psicótico: 2 años o indefinido."},
         {q:"¿Cuál es la duración mínima del trastorno depresivo persistente (distimia)?",r:"≥2 años en adultos, ≥1 año en niños/adolescentes (donde puede presentarse como irritabilidad). No más de 2 meses sin síntomas durante ese periodo."},
         {q:"¿Qué es la 'depresión doble'?",r:"Paciente con distimia crónica que además desarrolla episodios depresivos mayores superpuestos. Peor pronóstico."},
         {q:"¿Cuáles son los 4 síntomas afectivos nucleares del TDPM?",r:"1) Labilidad afectiva marcada, 2) irritabilidad o conflictos interpersonales, 3) ánimo deprimido/desesperanza, 4) ansiedad/tensión. Se requiere ≥1 de estos + totales ≥5 síntomas."},
         {q:"¿Cómo se confirma el diagnóstico de TDPM?",r:"Con registro diario PROSPECTIVO durante ≥2 ciclos sintomáticos. Los síntomas deben mejorar tras el inicio del sangrado y estar ausentes/mínimos en la semana posmenstrual."},
         {q:"¿Cuál es la edad mínima y máxima para diagnosticar TDDD?",r:"Mínimo 6 años, máximo 18 años. Inicio de síntomas antes de los 10 años es criterio obligatorio."},
         {q:"¿Por qué se creó el diagnóstico de TDDD?",r:"Para reducir el sobre-diagnóstico de trastorno bipolar pediátrico. Niños con irritabilidad crónica sin episodios maníacos discretos entran aquí, no en bipolar, evitando uso inapropiado de estabilizadores del ánimo."},
         {q:"¿Cuándo está indicada la TEC en depresión?",r:"Riesgo suicida agudo, depresión psicótica, catatonia, embarazo (1er trimestre especialmente), refractaria a múltiples fármacos, rechazo alimentario severo."},
         {q:"¿Qué ISRS se prefiere en embarazo y cuál evitar?",r:"Preferir sertralina. EVITAR paroxetina (asociada a defectos cardíacos)."},
         {q:"¿Qué fármaco tiene efecto rápido en depresión con suicidalidad aguda?",r:"Ketamina IV o esketamina intranasal (efecto en horas-días). Alternativa urgente junto con TEC."},
         {q:"¿En qué pacientes NO debe usarse bupropión?",r:"Antecedente de convulsiones, TCA activo con purgas (↓ umbral convulsivo), abstinencia aguda de alcohol o BZD. También no es ideal para ansiedad marcada."}
       ],
    quiz:[
       {p:"Mujer 35 años con 3 semanas de ánimo bajo, anhedonia, insomnio, fatiga, culpa y pensamientos de muerte. Sin episodios previos de manía. ¿Dx y 1ª línea?",
        o:["Distimia · TCC","TDM · ISRS + TCC","Bipolar I depresivo · quetiapina","Duelo · esperar"],r:1,
        x:"Episodio depresivo mayor (≥5 síntomas, ≥2 semanas, con ánimo bajo y anhedonia). Sin historia de manía → TDM, no bipolar. 1ª línea: ISRS + psicoterapia."},
       {p:"Paciente con TDM refractario a 2 ensayos de ISRS y 1 de IRSN. Actualmente con riesgo suicida alto y rechazo alimentario. ¿Mejor opción?",
        o:["Tercer ISRS","IMAO","TEC","Tricíclico"],r:2,
        x:"TEC está indicada en depresión refractaria + riesgo suicida agudo + rechazo alimentario. Efecto rápido, gold standard en estas situaciones."},
       {p:"Mujer 28 años con ánimo bajo persistente, fatiga, baja autoestima y desesperanza los últimos 3 años, sin periodos libres de síntomas mayores a un mes. No cumple criterios de episodio depresivo mayor. ¿Dx?",
        o:["TDM recurrente","Trastorno depresivo persistente (distimia)","Bipolar II","Adaptación"],r:1,
        x:"≥2 años de ánimo depresivo + ≥2 síntomas (fatiga, baja autoestima, desesperanza) sin periodos libres >2 meses = distimia."},
       {p:"Mujer 30 años con 1 año de irritabilidad severa, ansiedad y labilidad emocional los 7 días previos a su menstruación, que desaparece tras el sangrado. Registro diario en 2 ciclos confirma el patrón. ¿Dx y 1ª línea?",
        o:["TDM con patrón estacional · fototerapia","TDPM · ISRS (continuo o luteal)","Ansiedad generalizada · sertralina","Distimia · TCC"],r:1,
        x:"TDPM: síntomas severos cíclicos premenstruales + mejoría tras sangrado + confirmación prospectiva en ≥2 ciclos. ISRS es 1ª línea, puede usarse continuo o solo en fase luteal."},
       {p:"Niño de 8 años con rabietas severas 4 veces/semana, ánimo irritable persistente entre rabietas, en casa y escuela, durante 14 meses. Inicio a los 7 años. Sin episodios maníacos. ¿Dx?",
        o:["Trastorno bipolar pediátrico","Trastorno de desregulación disruptiva del ánimo (TDDD)","Trastorno negativista desafiante","TDAH"],r:1,
        x:"TDDD: rabietas severas ≥3/sem + irritabilidad crónica entre rabietas + ≥12 meses + ≥2 contextos + edad 6–18 con inicio antes de los 10. Se creó específicamente para evitar diagnosticar bipolar pediátrico en estos casos."},
       {p:"Paciente en tratamiento con ISRS 4 semanas, parcial mejoría pero disfunción sexual importante lo hace considerar abandonar. ¿Mejor opción?",
        o:["Agregar BZD","Cambiar a bupropión","Aumentar dosis del ISRS","Suspender todo antidepresivo"],r:1,
        x:"Bupropión es la mejor alternativa porque NO produce disfunción sexual (actúa sobre dopamina/noradrenalina, no serotonina). Mirtazapina es otra alternativa con bajo riesgo sexual."}
     ]
  }
};

// Agrupaciones por rama (psicosis vs neurosis)
var DECK_GROUPS={
  neurosis:["anxiety","toc","trauma","somaticos","tca","sueno","personalidad","impulsos","depresivos"],
  psicosis:["psicosis"],
  all:["psicosis","anxiety","toc","trauma","somaticos","tca"]
};

